<div id="pnl_edit">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_edit-caption">{{STATE_BEG}}Claim{{STATE_END}}</div>
		<a id="pnl_edit-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>


	<form id="pnl_edit-form">

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_claim_id" class="easyui-textbox" mapping="claim_id"  maxlength="36" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Code</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_claim_code" class="easyui-textbox" mapping="claim_code" uppercase="true" maxlength="50" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Activity</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_activity_id" class="easyui-combo" style="width: 400px" mapping="activity_id" display="activity_name" data-options="editable:false, valueField:'id', textField:'text' , required: false, invalidMessage: 'Activity required', prompt: '-- PILIH --'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_claim_descr" class="easyui-textbox" mapping="claim_descr"  maxlength="255" style="width: 400px" data-options="multiline: false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Employee</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_empl_id" class="easyui-combo" style="width: 400px" mapping="empl_id" display="empl_fullname" data-options="editable:false, valueField:'id', textField:'text' , required: false, invalidMessage: 'Employee required', prompt: '-- PILIH --'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Doc. Approval</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-cbo_docapprv_id" class="easyui-combo" style="width: 400px" mapping="docapprv_id" display="docapprv_name" data-options="editable:false, valueField:'id', textField:'text' , required: false, invalidMessage: 'Doc. Approval', prompt: '-- PILIH --'"  >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Reject Notes</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_claim_rejectnotes" class="easyui-textbox" mapping="claim_rejectnotes"  maxlength="255" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_claim_isrequest" class="easyui-checkbox c1" mapping="claim_isrequest" data-options="label: 'Request', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">RequestBy</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_claim_requestby" class="easyui-textbox" mapping="claim_requestby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">RequestDate</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_claim_requestdate" class="easyui-textbox" mapping="claim_requestdate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_claim_isapproved" class="easyui-checkbox c1" mapping="claim_isapproved" data-options="label: 'Approved', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Approve By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_claim_approveby" class="easyui-textbox" mapping="claim_approveby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Approve Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_claim_approvedate" class="easyui-textbox" mapping="claim_approvedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-chk_claim_isdeclined" class="easyui-checkbox c1" mapping="claim_isdeclined" data-options="label: 'Declined', labelPosition: 'after', checked: false , disabled: true">
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Decline By</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_claim_declineby" class="easyui-textbox" mapping="claim_declineby"  maxlength="14" style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_edit_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Decline Date</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_edit-txt_claim_declinedate" class="easyui-textbox" mapping="claim_declinedate"   style="width: 400px" data-options="multiline: false , disabled: true ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<a id="pnl_edit-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width">Simpan</a>
		</div>
	</div>	



		<div id="pnl_edit-detil" class="form_row" style="margin-top: 30px">
			<div class="form_label_col"></div>
			<div class="form_input_col detilbox" style="border: 0px solid black">
				<div class="fgtable-head" style="height: 25px; padding: 5px 0px 0px 5px">Detil Informations</div>
				<div class="fgtable-head-drow" style="height: 25px; padding: 5px 5px 0px 5px; " onclick="$ui.getPages().ITEMS['pnl_edit'].handler.detil_open('pnl_editclaimdtgrid')">
					<div id="pnl_edit-txt_claimdt_title" class="detilgrid-text">Date & Descr</div>
					<div id="pnl_edit-txt_claimdt_value" class="detilgrid-value claimdt_totalvalue">&nbsp;</div>
				</div>

			</div>		
		</div>		
		
		


	<div style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; display: flex; justify-content: space-between; padding: 10px 2px 2px 2px ">
		<div>
			<!-- letakkan tombol-tombol xtion disini -->
			<?php
			$customheaderxtion = __DIR__.'/claim-edit-customxtion.phtml'; 
			if (is_file($customheaderxtion)) {
				include $customheaderxtion;
			} else { ?>
			<a id="pnl_edit-btn_print" href="javascript:void(0)" class="easyui-linkbutton c8" style="margin-left:10px; margin-bottom: 10px;" data-options="iconCls:'icon-print'">print</a>
			
			
			
			<?php } ?>
		</div>
		<div>
			<a id="pnl_edit-btn_delete" class="easyui-linkbutton c5 fgta-button-delete" style="margin-bottom: 10px; margin-right: 10px">Hapus</a>
		</div>
	</div>

</div>

