<?php require_once dirname(__FILE__).'/claim-list.phtml' ?>
<?php require_once dirname(__FILE__).'/claim-edit.phtml' ?>
<?php require_once dirname(__FILE__).'/claim-claimdtgrid.phtml' ?>
<?php require_once dirname(__FILE__).'/claim-claimdtform.phtml' ?>



<?php
$customrecordstatus = __DIR__.'/claim-customrecordstatus.phtml'; 
if (is_file($customrecordstatus)) {
	include $customrecordstatus;
} else { ?>

<?php } ?>
