<div id="pnl_editdocapprvlevlform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editdocapprvlevlform-caption">{{STATE_BEG}}Level{{STATE_END}}</div>
		<a id="pnl_editdocapprvlevlform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editdocapprvlevlform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editdocapprvlevlform-form">

		<div class="form_row pnl_editdocapprvlevlform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdocapprvlevlform-txt_docapprvlevl_id" class="easyui-textbox" mapping="docapprvlevl_id" uppercase="true" maxlength="36"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editdocapprvlevlform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">SortOrder</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdocapprvlevlform-txt_docapprvlevl_sortorder" class="easyui-numberbox" mapping="docapprvlevl_sortorder" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editdocapprvlevlform_row" >
			<div class="form_label_col"></div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdocapprvlevlform-chk_docapprvlevl_isdisabled" class="easyui-checkbox c1" mapping="docapprvlevl_isdisabled" data-options="label: 'isDisabled', labelPosition: 'after', checked: false ">
			</div>
		</div>

		<div class="form_row pnl_editdocapprvlevlform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Employee</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdocapprvlevlform-cbo_empl_id" class="easyui-combo" style="width: 400px" mapping="empl_id" display="empl_fullname" data-options="editable:false, valueField:'id', textField:'text' , required: false, invalidMessage: 'Employee required', prompt: '-- PILIH --'" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editdocapprvlevlform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">docapprv_id</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editdocapprvlevlform-txt_docapprv_id" class="easyui-textbox" mapping="docapprv_id" uppercase="true" maxlength="36"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editdocapprvlevlform-autoadd" type="checkbox"><label for="pnl_editdocapprvlevlform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editdocapprvlevlform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/docapprv-docapprvlevlform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editdocapprvlevlform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editdocapprvlevlform-buttonbar-left">
			<a id="pnl_editdocapprvlevlform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editdocapprvlevlform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editdocapprvlevlform-buttonbar-middle">
			<a id="pnl_editdocapprvlevlform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editdocapprvlevlform-buttonbar-right">
			<a id="pnl_editdocapprvlevlform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
