<div id="pnl_editreqstionitmform">
	<div class="fgta-page-title" style="display: flex; align-items: center ">
		<div id="pnl_editreqstionitmform-caption">{{STATE_BEG}}Item{{STATE_END}}</div>
		<a id="pnl_editreqstionitmform-btn_edit" href="javascript:void(0)" class="easyui-linkbutton fgta-button-edit" style="margin-left:10px;" data-options="plain:true,iconCls:'fgta-icon-edit'">edit</a>
	</div>
	<div id="pnl_editreqstionitmform-title" class="fgta-page-subtitle">XXXXXXX</div>


	<form id="pnl_editreqstionitmform-form">

		<div class="form_row pnl_editreqstionitmform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editreqstionitmform-txt_reqstionitm_id" class="easyui-textbox" mapping="reqstionitm_id"  maxlength="36"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editreqstionitmform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Permintaan</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editreqstionitmform-cbo_typereq_id" class="easyui-combo" style="width: 400px" mapping="typereq_id" display="typereq_name" data-options="editable:false, valueField:'id', textField:'text' , required: true, invalidMessage: 'Permintaan required', prompt: '-- PILIH --'"  validType="requiredcombo['pnl_editreqstionitmform-cbo_typereq_id']" >
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editreqstionitmform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Name</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editreqstionitmform-txt_reqstionitm_name" class="easyui-textbox" mapping="reqstionitm_name"  maxlength="255"  style="width: 400px" data-options="multiline:false , required: true, invalidMessage: 'Name required' ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editreqstionitmform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Value</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editreqstionitmform-txt_reqstionitm_val" class="easyui-numberbox" mapping="reqstionitm_val" style="width: 400px; text-align:right" data-options="precision: 0, decimalSeparator:'.', groupSeparator:','  , required: true, invalidMessage: 'Value is require'">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>


		<div class="form_row pnl_editreqstionitmform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Attachment</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editreqstionitmform-fl_reqstionitm_file" class="easyui-filebox" mapping="reqstionitm_file" style="width: 400px" data-options="multiline: false  ">
				<div style="display: flex;">
					<a class="filedownloadlink" id="pnl_editreqstionitmform-fl_reqstionitm_file_link" style="cursor:pointer; margin-right: 10px; display: none">Download File</a>	
					<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
				</div>
				<img id="pnl_editreqstionitmform-fl_reqstionitm_file_img" style="width: 200px; width: 200px; border: 1px solid: #ccc; display:none">				
			</div>
		</div>

		<div class="form_row pnl_editreqstionitmform_row" >
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">Descr</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editreqstionitmform-txt_reqstionitm_descr" class="easyui-textbox" mapping="reqstionitm_descr"  maxlength="255"  style="width: 400px" data-options="multiline:false  ">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

		<div class="form_row pnl_editreqstionitmform_row" style="display: none">
			<div class="form_label_col"  style="border: 0px solid black; vertical-align: top; margin-top: 7px;">FK ID</div>
			<div class="form_input_col" style="border: 0px solid black">
				<input id="pnl_editreqstionitmform-txt_reqstion_id" class="easyui-textbox" mapping="reqstion_id"  maxlength="36"  style="width: 400px" data-options="multiline:false  , disabled: true">
				<div style="margin-top: 3px; margin-bottom: 5px; font-size: 0.75em; font-style: italic; color:#54381d;"></div>
			</div>
		</div>

	</form>


	<div class="form_row" style="margin-top: 30px">
		<div class="form_label_col"></div>
		<div class="form_input_col" style="border: 0px solid black">
			<div style="margin-bottom: 10px">
				<input id="pnl_editreqstionitmform-autoadd" type="checkbox"><label for="pnl_editreqstionitmform-autoadd">Otomatis tambah baru setelah berhasil disimpan</label>
			</div>
			<div>
				<a id="pnl_editreqstionitmform-btn_save" class="easyui-linkbutton c1 fgta-button-save" style="width: 100px">Simpan</a>
			</div>
		</div>
	</div>	


	<?php
	$custombuttonbar = __DIR__.'/reqstion-reqstionitmform-custombuttonbar.phtml';
	if (is_file($custombuttonbar)) {
		include $custombuttonbar;
	} else { ?>
	<div id="pnl_editreqstionitmform-buttonbar" style="margin-top: 30px; margin-left:-5px; margin-right: -5px; background-color: #cccccc; height: 40px; display: flex; justify-content: space-between; padding: 5px 2px 2px 2px ">
		<div id="pnl_editreqstionitmform-buttonbar-left">
			<a id="pnl_editreqstionitmform-btn_prev" class="easyui-linkbutton c8 fgta-button-detilprev" style="width: 50px">Prev</a>
			<a id="pnl_editreqstionitmform-btn_next" class="easyui-linkbutton c8 fgta-button-detilnext" style="width: 50px">Next</a>
		</div>

		<div id="pnl_editreqstionitmform-buttonbar-middle">
			<a id="pnl_editreqstionitmform-btn_addnew" class="easyui-linkbutton c8 fgta-button-detiladd" style="width: 100px">Tambah Baru</a>
		</div>

		<div id="pnl_editreqstionitmform-buttonbar-right">
			<a id="pnl_editreqstionitmform-btn_delete" class="easyui-linkbutton c5" style="width: 100px">Hapus</a>
		</div>
	</div>
	<?php } ?>




</div>	
